<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NCode.Identity.Persistence</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Persistence.Abstractions\NCode.Persistence.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />
    </ItemGroup>

</Project>
