<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Collections.Providers\NCode.Collections.Providers.csproj" />
        <ProjectReference Include="..\NCode.Identity.JsonWebTokens\NCode.Identity.JsonWebTokens.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Authentication.Abstractions\NCode.Identity.OpenId.Authentication.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Messages.Abstractions\NCode.Identity.OpenId.Messages.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Persistence.Abstractions\NCode.Identity.OpenId.Persistence.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.PropertyBag\NCode.PropertyBag.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="IdGen" Version="3.0.7" />
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
      <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
      <PackageReference Include="NCode.Base64Url" Version="2.0.0" />
      <PackageReference Include="NCode.CryptoMemory" Version="3.1.0" />
    </ItemGroup>

</Project>
