<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.JsonWebTokens\NCode.Identity.JsonWebTokens.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Authentication.Abstractions\NCode.Identity.OpenId.Authentication.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Persistence.Abstractions\NCode.Identity.OpenId.Persistence.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.PropertyBag\NCode.PropertyBag.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="IdGen" Version="3.0.7" />
      <PackageReference Include="JetBrains.Annotations" Version="2024.2.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
      <PackageReference Include="NCode.Base64Url" Version="1.1.2" />
      <PackageReference Include="NCode.CryptoMemory" Version="2.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Errors\" />
    </ItemGroup>

</Project>
