<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.Jose\NCode.Identity.Jose.csproj" />
        <ProjectReference Include="..\NCode.Identity.JsonWebTokens\NCode.Identity.JsonWebTokens.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Authentication\NCode.Identity.OpenId.Authentication.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Core\NCode.Identity.OpenId.Core.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Management\NCode.Identity.OpenId.Management.csproj" />
        <ProjectReference Include="..\NCode.Identity.Secrets.Persistence\NCode.Identity.Secrets.Persistence.csproj" />
        <ProjectReference Include="..\NCode.Identity.Secrets\NCode.Identity.Secrets.csproj" />
        <ProjectReference Include="..\NCode.Identity\NCode.Identity.csproj" />
        <ProjectReference Include="..\NCode.Mediator\NCode.Mediator.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
    </ItemGroup>

</Project>
