<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.Jose.Abstractions\NCode.Identity.Jose.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Primitives" />
        <PackageReference Include="NCode.Base64Url" />
        <PackageReference Include="NCode.Buffers" />
        <PackageReference Include="NCode.Collections.Providers" />
        <PackageReference Include="NCode.Disposables" />
        <PackageReference Include="Nerdbank.Streams" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="*\AlgorithmCodes.*.cs">
            <DependentUpon>AlgorithmCodes.cs</DependentUpon>
        </Compile>
        <Compile Update="JoseSerializer.*.cs">
            <DependentUpon>JoseSerializer.cs</DependentUpon>
        </Compile>
        <Compile Update="*\SecretKeyReader.*.cs">
            <DependentUpon>SecretKeyReader.cs</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
