<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>NCode.Identity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!-- https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore -->
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Collections.Providers.Abstractions\NCode.Collections.Providers.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
    </ItemGroup>

</Project>
