<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>NCode.Identity.OpenId</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <!-- https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore -->
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="IdGen.DependencyInjection" />
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Primitives" />
        <PackageReference Include="NCode.Base64Url" />
        <PackageReference Include="NCode.Disposables" />
        <PackageReference Include="NCode.PasswordGenerator" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
        <PackageReference Include="System.Linq.Async" />
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
        <PackageReference Include="SystemTextJsonPatch" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.JsonWebTokens\NCode.Identity.JsonWebTokens.csproj" />
        <ProjectReference Include="..\NCode.Identity.Jose.Abstractions\NCode.Identity.Jose.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Abstractions\NCode.Identity.OpenId.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Messages.Abstractions\NCode.Identity.OpenId.Messages.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Persistence.Abstractions\NCode.Identity.OpenId.Persistence.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.Secrets.Persistence.Abstractions\NCode.Identity.Secrets.Persistence.Abstractions.csproj" />
    </ItemGroup>
</Project>
