<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>NCode.Identity.OpenId.Authentication</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.Jose.Abstractions\NCode.Identity.Jose.Abstractions.csproj" />
        <ProjectReference Include="..\NCode.Identity.OpenId.Abstractions\NCode.Identity.OpenId.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
      <PackageReference Include="NCode.Disposables" Version="5.3.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="OpenIdConstants.*.cs">
        <DependentUpon>OpenIdConstants.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
