<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Identity.Secrets.Abstractions\NCode.Identity.Secrets.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="NCode.Buffers" />
        <PackageReference Include="NCode.Collections.Providers" />
        <PackageReference Include="NCode.Extensions.DataProtection" />
    </ItemGroup>
</Project>
