<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NCode.Collections.Providers\NCode.Collections.Providers.csproj" />
      <ProjectReference Include="..\NCode.Identity.Abstractions\NCode.Identity.Abstractions.csproj" />
      <ProjectReference Include="..\NCode.Identity.Jose.Abstractions\NCode.Identity.Jose.Abstractions.csproj" />
      <ProjectReference Include="..\NCode.Registration\NCode.Registration.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NCode.Base64Url" Version="2.0.1" />
      <PackageReference Include="NCode.Buffers" Version="4.0.0" />
    </ItemGroup>

</Project>
