// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NCode.Identity.OpenId.Persistence.EntityFramework;

#nullable disable

namespace NCode.Identity.OpenId.Playground.Migrations
{
    [DbContext(typeof(OpenIdDbContext))]
    partial class OpenIdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedClientId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedClientId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientGrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResourceServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScopesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ResourceServerId");

                    b.HasIndex("TenantId", "ClientId", "ResourceServerId")
                        .IsUnique();

                    b.ToTable("ClientGrants");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientSecretEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecretId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SecretId");

                    b.HasIndex("TenantId", "ClientId", "SecretId")
                        .IsUnique();

                    b.ToTable("ClientSecrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.FederatedIdentityEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("FederatedIdentityId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("FederatedPrincipalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinKey")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedFederatedIdentityId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIssuer")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedJoinKey")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSubject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FederatedPrincipalId");

                    b.HasIndex("NormalizedFederatedIdentityId")
                        .IsUnique();

                    b.HasIndex("NormalizedJoinKey");

                    b.HasIndex("NormalizedIssuer", "NormalizedSubject")
                        .IsUnique();

                    b.ToTable("FederatedIdentities");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.FederatedPrincipalEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPrincipalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedPrincipalId")
                        .IsUnique();

                    b.ToTable("FederatedPrincipals");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.GrantEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ConsumedWhen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiresWhen")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedGrantId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedSubjectId")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedWhen")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresWhen");

                    b.HasIndex("NormalizedGrantId")
                        .IsUnique();

                    b.HasIndex("GrantType", "HashedKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "ClientId");

                    b.HasIndex("TenantId", "NormalizedSubjectId");

                    b.ToTable("Grants");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ResourceServerEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedIdentifier")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedResourceServerId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceServerId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopesConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedIdentifier")
                        .IsUnique();

                    b.HasIndex("TenantId", "NormalizedResourceServerId")
                        .IsUnique();

                    b.ToTable("ResourceServers");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.RoleAssignmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedAssignmentId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedPrincipalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedResourceId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedRoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NormalizedAssignmentId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ResourceType", "NormalizedResourceId");

                    b.HasIndex("TenantId", "NormalizedPrincipalId", "NormalizedRoleName", "ResourceType", "NormalizedResourceId")
                        .IsUnique();

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ScopeEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResourceServerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ResourceServerId", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.SecretEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Algorithm")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedWhen")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncodedValue")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresWhen")
                        .HasColumnType("TEXT");

                    b.Property<int>("KeySizeBits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedSecretId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Use")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSecretId")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ServerEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedServerId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedServerId")
                        .IsUnique();

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ServerSecretEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecretId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecretId");

                    b.HasIndex("ServerId", "SecretId")
                        .IsUnique();

                    b.ToTable("ServerSecrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainName")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedDomainName")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTenantId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsConcurrencyToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedDomainName")
                        .IsUnique()
                        .HasFilter("NormalizedDomainName IS NOT NULL");

                    b.HasIndex("NormalizedTenantId")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantSecretEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SecretId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TenantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecretId");

                    b.HasIndex("TenantId", "SecretId")
                        .IsUnique();

                    b.ToTable("TenantSecrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientGrantEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ResourceServerEntity", "ResourceServer")
                        .WithMany()
                        .HasForeignKey("ResourceServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ResourceServer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientSecretEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", "Client")
                        .WithMany("Secrets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.SecretEntity", "Secret")
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Secret");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.FederatedIdentityEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.FederatedPrincipalEntity", "FederatedPrincipal")
                        .WithMany()
                        .HasForeignKey("FederatedPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FederatedPrincipal");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.GrantEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ResourceServerEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.RoleAssignmentEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ScopeEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ResourceServerEntity", "ResourceServer")
                        .WithMany("Scopes")
                        .HasForeignKey("ResourceServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceServer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ServerSecretEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.SecretEntity", "Secret")
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ServerEntity", "Server")
                        .WithMany("Secrets")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secret");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantSecretEntity", b =>
                {
                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.SecretEntity", "Secret")
                        .WithMany()
                        .HasForeignKey("SecretId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", "Tenant")
                        .WithMany("Secrets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Secret");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ClientEntity", b =>
                {
                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ResourceServerEntity", b =>
                {
                    b.Navigation("Scopes");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.ServerEntity", b =>
                {
                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("NCode.Identity.OpenId.Persistence.EntityFramework.Entities.TenantEntity", b =>
                {
                    b.Navigation("Secrets");
                });
#pragma warning restore 612, 618
        }
    }
}
