<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NCode.Collections.Providers\NCode.Collections.Providers.csproj"/>
        <ProjectReference Include="..\NCode.Identity.Jose.Abstractions\NCode.Identity.Jose.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="All" />
        <PackageReference Include="Microsoft.AspNetCore.DataProtection" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="10.0.2" />
        <PackageReference Include="NCode.Base64Url" Version="2.0.1" />
        <PackageReference Include="NCode.Buffers" Version="4.0.0" />
        <PackageReference Include="NCode.Disposables" Version="5.3.0" />
        <PackageReference Include="Nerdbank.Streams" Version="2.13.16" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="*\AlgorithmCodes.*.cs">
            <DependentUpon>AlgorithmCodes.cs</DependentUpon>
        </Compile>
        <Compile Update="JoseSerializer.*.cs">
            <DependentUpon>JoseSerializer.cs</DependentUpon>
        </Compile>
        <Compile Update="*\SecretKeyReader.*.cs">
            <DependentUpon>SecretKeyReader.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
